name:                conway-wechsler
version:             0.1.0.0
github:              "dylan-thinnes/conway-wechsler"
license:             MIT
author:              "Dylan Thinnes"
maintainer:          "dylan.thinnes@protonmail.com"
copyright:           "2019 Dylan Thinnes"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dylan-thinnes/conway-wechsler#readme>

dependencies:
- base >= 4.7 && < 5
- math-parse
- text >= 1.2 && < 2
- containers >= 0.6 && < 1

executables:
  conway-wechsler:
    main:                Main.hs
    source-dirs:         app
