#!/bin/bash
if [ -x "$(command -v stackr)" ]; then
  echo 'Stack is detected as being installed. Running GHCi through stack.'
  stack ghci --ghci-options -imath-parser conway-wechsler.hs
elif [ -x "$(command -v ghc)" ]; then
  echo 'GHCi is detected as being installed standalone. Running.'
  ghci -imath-parser conway-wechsler.hs
else
  echo 'Neither stack nor ghci are detected as being installed.'
  echo 'Please refer to https://haskell-lang.org/get-started to install Haskell.'
  echo 'If you are SURE you have ghci / stack installed, please open an issue on https://github.com/dylan-thinnes/conway-wechsler'
fi
